development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f2e35808d4600f1b6a9e7abfc3b8d10f@spinyfin.redistogo.com:10981/
  channel_prefix: zlack_production
